// global mcap constants
mCAP.MCAP = 'MCAP';
mCAP.APNS = 'APNS';
mCAP.GCM = 'GCM';

// component types
mCAP.ASSET = 'ASSET';
mCAP.CHANNEL = 'CHANNEL';
mCAP.PIPELINE = 'PIPELINE';
mCAP.SERVICE_CONNECTION = 'SERVICE_CONNECTION';
mCAP.META_MODEL = 'META_MODEL';
mCAP.SCHEDULER_TASK = 'SCHEDULER_TASK';
mCAP.PUSH_SERVICE = 'PUSH_SERVICE';